package com.tarakki.support.enums;

public enum IssueType {
    LOGIN_ISSUE,
    SIGNUP_ERROR,
    PASSWORD_RESET_LINK_NOT_RECEIVED,
    TWO_FACTOR_AUTH_LOCKOUT,
    DELETE_OR_DEACTIVATE_ACCOUNT,
    FILE_UPLOAD_ERROR,
    BOARD_PERFORMANCE,
    AUTOMATION_INTEGRATION_ERROR,
    LOST_DATA_OR_MISSING_ITEMS,
    MEMBER_INVITE_ISSUE,
    PERMISSION_MISMATCH,
    NOTIFICATION_ISSUE,
    GENERAL_QUESTION,
    FEATURE_REQUEST,
    BUG_REPORT,
    OTHER
}